// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAovZSvKpMrLceqXLVerfk6-3SljMvwPao',
    appId: '1:803053835663:web:91c8d8eac7ca22e288e7fa',
    messagingSenderId: '803053835663',
    projectId: 'nonapbn25',
    authDomain: 'nonapbn25.firebaseapp.com',
    databaseURL: 'https://nonapbn25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nonapbn25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUaHw-YbGFFS2I-brucdtj5JeK0vJMuaQ',
    appId: '1:803053835663:android:31a11fff8e96f69a88e7fa',
    messagingSenderId: '803053835663',
    projectId: 'nonapbn25',
    databaseURL: 'https://nonapbn25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nonapbn25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4llRkHCW3Q2HrEermj9EERC3mVTpj2Gw',
    appId: '1:803053835663:ios:4bf994da130e142c88e7fa',
    messagingSenderId: '803053835663',
    projectId: 'nonapbn25',
    databaseURL: 'https://nonapbn25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nonapbn25.firebasestorage.app',
    iosClientId: '803053835663-30u4hbv5vp8isldj5ncbdakdsrbbaj9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4llRkHCW3Q2HrEermj9EERC3mVTpj2Gw',
    appId: '1:803053835663:ios:4bf994da130e142c88e7fa',
    messagingSenderId: '803053835663',
    projectId: 'nonapbn25',
    databaseURL: 'https://nonapbn25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nonapbn25.firebasestorage.app',
    iosClientId: '803053835663-30u4hbv5vp8isldj5ncbdakdsrbbaj9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAovZSvKpMrLceqXLVerfk6-3SljMvwPao',
    appId: '1:803053835663:web:6cc57a52b1a6862e88e7fa',
    messagingSenderId: '803053835663',
    projectId: 'nonapbn25',
    authDomain: 'nonapbn25.firebaseapp.com',
    databaseURL: 'https://nonapbn25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nonapbn25.firebasestorage.app',
  );
}
